SELECT COUNT(*) FROM LOAN;
SELECT * FROM LOAN;


-- TOTAL LOAN AMOUNT FUNDED
SELECT CONCAT(ROUND(SUM(FUNDEDAMOUNT)/1000000)," ","M") AS TOTAL_LAON_AMOUNT_FUNDED  FROM LOAN;

-- TOTAL LOANS
SELECT COUNT(FUNDEDAMOUNT) AS TOTAL_LOANS FROM LOAN;

-- TOTAL COLLECTION
SELECT CONCAT(ROUND(SUM(TOTALPYMNT)/1000000)," " ,"M") AS TOTAL_COLLECTION FROM LOAN;

-- DELINQUENT LOAN RATE
SELECT CONCAT(ROUND(( SUM(ISDELINQUENTLOAN = "Y")/COUNT(*)*100),2),"%") AS DELINQUENT_LOAN_RATE FROM LOAN;

-- DEFAULT LOAN RATE
SELECT CONCAT(ROUND(( SUM(ISDEFAULTLOAN = "Y")/COUNT(*)*100),2),"%") AS DEFAULT_LOAN_RATE FROM LOAN;

-- STATE WISE LOAN
SELECT STATENAME , CONCAT(ROUND(SUM(FUNDEDAMOUNT)/1000000,2)," ","M") AS FUNDED_AMOUNT FROM LOAN
GROUP BY STATENAME
ORDER BY ROUND(SUM(FUNDEDAMOUNT)/1000000,2) DESC ;

-- DISBURSEMENT TREND
SELECT YEAR(DISBURSEMENTDATE) AS YEAR , CONCAT(ROUND(SUM(FUNDEDAMOUNT)/1000000,2)," ","M") AS FUNDED_AMOUNT FROM LOAN
GROUP BY YEAR
ORDER BY ROUND(SUM(FUNDEDAMOUNT)/1000000,2) DESC ;

-- GRADE WISE LOAN
SELECT GRADE , CONCAT(ROUND(SUM(FUNDEDAMOUNT)/1000000,2)," ","M") AS FUNDED_AMOUNT FROM LOAN
GROUP BY GRADE
ORDER BY ROUND(SUM(FUNDEDAMOUNT)/1000000,2) DESC ;

-- LOAN STATUS WISE LOAN
SELECT LOANSTATUS, CONCAT(ROUND(SUM(FUNDEDAMOUNT)/1000000,2)," ","M") AS FUNDED_AMOUNT FROM LOAN
GROUP BY LOANSTATUS
ORDER BY ROUND(SUM(FUNDEDAMOUNT)/1000000,2) DESC ;

-- LOAN MATURITY
SELECT YEAR(MATURITYDATE) AS MATURITY_YEAR, CONCAT(ROUND(SUM(FUNDEDAMOUNT)/1000000,2)," ","M") AS FUNDED_AMOUNT FROM LOAN
GROUP BY MATURITY_YEAR
ORDER BY ROUND(SUM(FUNDEDAMOUNT)/1000000,2) DESC ;








